-- Assignment 2
 use mavenmovies;
 
 -- 1 : Retrieve the total number of rentals made in the Sakila database.
 select count(rental_id) from rental;
 
 -- 2 : Find the average rental duration (in days) of movies rented from the Sakila database
 select avg(rental_duration) as days from film ;
 
 -- 3 : Display the first name and last name of customers in uppercase. 
 select upper(first_name) ,upper(last_name) from customer;
 
 -- 4 : Extract the month from the rental date and display it alongside the rental ID.
 select rental_id , month(rental_date) as Month from rental;
 
 -- 5 : Retrieve the count of rentals for each customer (display customer ID and the count of rentals). 
 select customer_id, count(rental_id) as count_of_rentals from rental group by customer_id;
 
 -- 6 : Find the total revenue generated by each store. 
 select store_id ,sum(amount) from payment 
     inner join  
         rental on payment.rental_id = rental.rental_id 
             inner join 
				staff on rental.staff_id = staff.staff_id 
                     inner join 
                        store on staff.store_id = store.store_id ;  
                        
 -- 7 : Display the title of the movie, customer s first name, and last name who rented it.
 select concat(first_name ,last_name) as Full_name,title from customer
    inner join
       rental on customer.customer_id = rental.customer_id
           inner join
               inventory on rental.inventory_id = inventory.inventory_id 
                    inner join film on inventory.film_id = film.film_id;
                    
-- 8 : Retrieve the names of all actors who have appeared in the film "Gone with the Wind
select concat(first_name ,last_name) as actor_name
     from 
        actor 
            inner join
                 film_actor 
                 on actor.actor_id = film_actor.actor_id
                    inner join 
                       film on film_actor.film_id = film.film_id 
                         where 
                           title in ("GOLDFINGER SENSIBILITY");
                           
-- 9 : Determine the total number of rentals for each category of movies.
-- JOIN film_category, film, and rental tables, then use cOUNT () and GROUP BY. 
-- select category, count(rental_id) from film inner join film_category on film.film_id = film_category.film_id inner join rental on 

-- 10 : Find the average rental rate of movies in each language. 
     select name ,avg(rental_rate) from film inner join language on film.language_id = language.language_id group by name;
     
-- 11 : Retrieve the customer names along with the total amount they've spent on rentals. 
   
   SELECT 
    first_name, last_name, SUM(amount)
FROM
    customer AS c
        INNER JOIN
    payment AS p ON c.customer_id = p.customer_id
        INNER JOIN
    rental AS r ON p.rental_id = r.rental_id
GROUP BY c.customer_id;   

-- 12 : List the titles of movies rented by each customer in a particular city (e.g., 'London'). 
 
SELECT 
    title, first_name, last_name, city
FROM
    film AS f
        INNER JOIN
    inventory AS i ON f.film_id = i.film_id
        INNER JOIN
    rental AS r ON i.inventory_id = r.inventory_id
        INNER JOIN
    customer AS c ON c.customer_id = r.customer_id
        INNER JOIN
    address AS a ON a.address_id = c.address_id
        INNER JOIN
    city ON a.city_id = city.city_id
; 

-- 13 : Display the top 5 rented movies along with the number of times they've been rented. 
  
SELECT 
    title, COUNT(rental_id)
FROM
    film AS f
        INNER JOIN
    inventory AS i ON f.film_id = i.film_id
        INNER JOIN
    rental AS r ON i.inventory_id = r.inventory_id
GROUP BY i.film_id
 order by  count(rental_id) desc
LIMIT 5;

-- 14 : Determine the customers who have rented movies from both stores (store ID 1 and store ID 2). 

SELECT 
    first_name, last_name
FROM
    customer AS c
        INNER JOIN
    rental as r on c.customer_id = r.customer_id 
    inner join
    inventory as i on i.inventory_id = r.inventory_id where i.store_id = 1 & 2;


